version: '3'

services:
    symfony:
        image: php:7.4-alpine
        working_dir: /var/www
        command: vendor/bin/server watch 0.0.0.0:8080 --adapter=App\\AppKernelAdapter
        ports:
            - 8080:8080
        volumes:
            - .:/var/www
