app_index:
    path: /
    controller: App\Controller\HomeController::index

app_ruc_individual:
  path: /api/v1/ruc/{ruc<\d{11}>}
  controller: App\Controller\ConsultController::ruc

app_userSol:
  path: /api/v1/user-sol/{ruc<\d{11}>}/{user}
  controller: App\Controller\ConsultController::userSol

app_dni_individual:
  path: /api/v1/dni/{dni<\d{8}>}
  controller: App\Controller\ConsultController::dni

app_ruc_multiple:
  path: /api/v1/ruc
  controller: App\Controller\ConsultMultipleController::ruc
  methods: POST

app_dni_multiple:
  path: /api/v1/dni
  controller: App\Controller\ConsultMultipleController::dni
  methods: POST

app_graphql:
  path: /api/graph
  controller: App\Controller\GraphController::query
  methods: POST