name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: PHP Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 7.3
        extensions: pcntl
    - run: composer install
    - run: php bin/phpunit
      env:
        MOCK_URL: ${{ secrets.MockServer }}
